### ISSUE TITLE
Trying to use batchcam in night

### ISSUE THREAD

**Issue by ratatouillex** [usakhelo/batchcam#9]
Hello,
I love Batchcam and use it every day.
Now we have huge 3dsmax files ready to render but we have to do it in night while workstations are idle.
But can't figure out what to do,
Now we need to open the 3dsmax files one after another and hit render in batchcam. Trying to automate this process.

Thank you.

**Comment by usakhelo** [comment]
Hi @ratatouillex ,
Sorry it took me forever to answer. I'm not using batchcam myself, that's why it's not updated very often.
Could you take a look at this script - http://www.scriptspot.com/3ds-max/scripts/mfrender
I add the support of the script in BatchCam, but I don't think anyone has ever tested that - http://sergepogosyan.com/batchcam/batchcam-1.9.20.html

**Comment by ratatouillex** [comment]
Hello,
Thanks for your reply.

I hope he is alive but lots of artists died in covid.
Even though his website is not alive too. maybe because of not paying the bill.
maybe he isn't in this world anymore.

Btw, please help the community in his absence. Edit the mfrender or make similar things.
So, that we could do what we are trying to do.

Also, if 'batch Camera render' is down like the mfrender, that will be a nightmare for us. we use it every day.
We don't have any alternative to batchcam. we are using the 1.18 in 3dsmax 2023.

Also, I have sent an email.

**Comment by usakhelo** [comment]
I'm sure he alive and he's doing good.

I made some quick changes to the script and it seems to be working in 2023 with some Batchcam I have installed. Feel free to try and let me know if how it works.
I also changed UI a bit, hopefully you'll figure it out.

[mfrender_batchcam.zip](https://github.com/usakhelo/batchcam/files/12211313/mfrender_batchcam.zip)

**Comment by ratatouillex** [comment]
Hello,
Thanks for your reply.
And you actually saved me. The Functions I need are working at this moment.
Like, I have several files Fully prepared and ready to render in batchcam are rendered very well in loop with its own settings.

_Global Override settings_ don't work with batchcam.
_Other Settings_ doesn't work with batchcam.

it also shows this error window when,
![image](https://github.com/usakhelo/batchcam/assets/61550040/3f275b31-6165-4b87-970f-06fb2e1612bb)
1. Hit batchcamera Button then it asks for yes or no, when pressed NO.
2. rendering completed normally.
3. when i canceled rendering.

**Comment by ratatouillex** [comment]
![image](https://github.com/usakhelo/batchcam/assets/61550040/0cd67a4f-6a00-4595-93db-1938c3abc1db)
[Multiple maxfile with batchcam.zip](https://github.com/usakhelo/batchcam/files/12280103/Multiple.maxfile.with.batchcam.zip)

Because other functions are not working with batchcam, I just make it a little clean and easier to understand.
I'm not an expert. so, didn't update any code at all.
But the automatic shutdown is a nice function if it works with batchcam.

**Comment by usakhelo** [comment]
@ratatouillex
Regarding your two issues - I tried to fix the first issue, line number 253 and the test version is in the attachment.
You are right about the second issue - you need to run BatchCam first manually. There's no fix for that issue, and the problem is I don't have access to 3ds max at the moment to find a nice solution. So, current solution is to run Batchcam script first, and then mf_render.

Please test if you have time and let me know how it works.
[mfrender_batchcam.zip](https://github.com/usakhelo/batchcam/files/12328729/mfrender_batchcam.zip)

**Comment by ratatouillex** [comment]
@usakhelo 
Thanks you very much that you helped even though you don't have 3dsmax now.
And the good news is that its works.

i have setup a button to execute the batchcam first then mfrender. so, the second issue resolved.
and Shutdowning 3dsmax and pc after render is working too.

Bravo. Its looks complete now.
Thank you very much again!
